spring:
    profiles:
        active: dev
    http:
           encoding:
               charset: UTF-8
               force: true
               enabled: true
logging:
  level:
     com.gsb.sundry.dao : debug