server:
  port: 8080


spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource

    thymeleaf:
        cache: true
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8
        content-type: text/html


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.gsb.sundry.pojo #注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
